# Generated by Django 4.0.6 on 2022-08-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.townlist'),
        ),
    ]
